DECLARE
V_HIREDATE EMP.HIREDATE%TYPE;
V_EXP INT;
v_empno emp.empno%type;

BEGIN
    v_empno := &empno;
    SELECT HIREDATE INTO V_HIREDATE FROM EMP WHERE EMPNO = V_EMPNO;
    V_EXP := TRUNC((SYSDATE-V_HIREDATE)/365);
    dbms_output.put_line('experience is '||v_exp);
    IF V_EXP>40 THEN
    DELETE FROM EMP WHERE EMPNO=V_EMPNO;
    DBMS_OUTPUT.PUT_LINE('RECORD DELETED SUCCESSFULLY');
    ELSE
    DBMS_OUTPUT.PUT_LINE ('RECORD NOT DELETED');
    END IF;
END;
/