DECLARE
V_SID STUDENT.SID%TYPE;
V_SNAME STUDENT.SNAME%TYPE;
V_SCITY STUDENT.SCITY%TYPE;
BEGIN
    V_SID := &SID;
    V_SNAME := '&SNAME';
    V_SCITY := '&SCITY';
    INSERT INTO STUDENT VALUES(V_SID,V_SNAME,V_SCITY);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('RECORD INSERTED SUCCESSFULLY');
END;
/